# Generated by Django 4.0.6 on 2022-08-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_request',
            field=models.JSONField(null=True),
        ),
    ]
